### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by yrcrcy** [gbaier/rs_img_synth#1]
Thank you for your contribution, I made an error while executing the following command,
python -m torch.distributed.launch --nproc_per_node=8 train.py \
--epochs 200 \
--batch_size 32 \
--model_cap 64 \
--lbda 5.0 \
--num_workers 0 \
--dataset 'dfc' \
--dataroot './data/DFC_Public_Dataset' \
--input 'seg' \
--output 'sar‘

This is a display error：

File "/data-input/DEM/rs_img/datasets/dfc.py", line 97, in __getitem__

sample["rgb"] = self.s2_as_rgb(sample.pop("s2"))

AttributeError: 'DFC2020' object has no attribute 's2_as_rgb'

I have operated in accordance with the readme you gave me. Could you please tell me how to solve this problem? I am looking forward to your reply.

**Comment by gbaier** [comment]
Sorry, this was entirely my bad. I did some refactoring and didn't properly test the code.

https://github.com/gbaier/rs_img_synth/commit/4438a9436850a1de28525c4e5d0590b721c2110d should fix your issue.

**Comment by yrcrcy** [comment]
Thanks for your contribution. The errors have been solved according to the code you gave.

**Comment by yrcrcy** [comment]
Thanks for your contribution. The errors have been solved according to the code you gave.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gbaier/rs_img_synth"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 中午12:42
收件人:&nbsp;"gbaier/rs_img_synth"<rs_img_synth@noreply.github.com&gt;;
抄送:&nbsp;"Clown"<1572112413@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gbaier/rs_img_synth] questions (#1)





 
Sorry, this was entirely my bad. I did some refactoring and didn't properly test the code.
 
4438a94 should fix your issue.
